# Generated by Django 6.0.2 on 2026-08-29 06:21

import django.utils.timezone
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingsignup',
            name='code',
            field=models.CharField(default=user.models.generate_signup_code, max_length=6),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='code_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingsignup',
            name='code_sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
