# Generated by Django 6.0.2 on 2026-03-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='daysSinceCreated',
        ),
    ]
