# Generated by Django 6.0.2 on 2026-03-04 03:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_dayssincecreated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'completed'], name='tasks_task_user_id_f226ed_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['dateDeadline'], name='tasks_task_dateDea_dfeda3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_task_per_user'),
        ),
    ]
