# Generated by Django 6.0.2 on 2026-03-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_tasks_task_user_id_f226ed_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-dateCreated']},
        ),
    ]
