# Generated by Django 6.0.2 on 2026-08-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
