# Generated by Django 6.0.2 on 2026-08-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
